-- migrate:up

CREATE TABLE campaign (
  code VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  translations JSONB NOT NULL
);

CREATE TABLE scenario (
  code VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  translations JSONB NOT NULL,
  campaign_code VARCHAR(255) REFERENCES campaign(code)
);

CREATE TABLE campaign_scenario (
  campaign_code VARCHAR(255) NOT NULL REFERENCES campaign(code) ON DELETE CASCADE,
  scenario_code VARCHAR(255) NOT NULL REFERENCES scenario(code) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (campaign_code, scenario_code)
);

CREATE TABLE scenario_encounter_set (
  scenario_code VARCHAR(255) NOT NULL REFERENCES scenario(code) ON DELETE CASCADE,
  encounter_code VARCHAR(255) NOT NULL REFERENCES encounter_set(code) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (scenario_code, encounter_code)
);

CREATE TABLE scenario_encounter_set_card (
  scenario_code VARCHAR(255) NOT NULL,
  encounter_code VARCHAR(255) NOT NULL,
  card_id VARCHAR(255) NOT NULL REFERENCES card(id) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (scenario_code, encounter_code, card_id),
  FOREIGN KEY (scenario_code, encounter_code) REFERENCES scenario_encounter_set(scenario_code, encounter_code) ON DELETE CASCADE
);

CREATE TABLE errata (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position INT NOT NULL,
  type VARCHAR(36) NOT NULL,
  section VARCHAR(255),
  ruling TEXT NOT NULL,
  citation TEXT NOT NULL,
  CONSTRAINT errata_type_check CHECK (type IN ('campaign_errata', 'card_errata', 'rulebook_errata')),
  CONSTRAINT errata_rulebook_section_check CHECK (
    (type = 'rulebook_errata' AND section IS NOT NULL)
    OR (type <> 'rulebook_errata' AND section IS NULL)
  )
);

CREATE TABLE errata_card (
  errata_id INT NOT NULL REFERENCES errata(id) ON DELETE CASCADE,
  card_id VARCHAR(255) NOT NULL REFERENCES card(id) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (errata_id, card_id)
);

CREATE TABLE errata_cycle (
  errata_id INT NOT NULL REFERENCES errata(id) ON DELETE CASCADE,
  cycle_code VARCHAR(255) NOT NULL REFERENCES cycle(code) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (errata_id, cycle_code)
);

CREATE TABLE errata_scenario (
  errata_id INT NOT NULL REFERENCES errata(id) ON DELETE CASCADE,
  scenario_code VARCHAR(255) NOT NULL REFERENCES scenario(code) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (errata_id, scenario_code)
);

CREATE TABLE faq (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position INT NOT NULL,
  type VARCHAR(36) DEFAULT 'faq' NOT NULL,
  question TEXT NOT NULL,
  ruling TEXT NOT NULL,
  citation TEXT NOT NULL,
  CONSTRAINT faq_type_check CHECK (type = 'faq')
);

CREATE TABLE faq_card (
  faq_id INT NOT NULL REFERENCES faq(id) ON DELETE CASCADE,
  card_id VARCHAR(255) NOT NULL REFERENCES card(id) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (faq_id, card_id)
);

CREATE TABLE faq_cycle (
  faq_id INT NOT NULL REFERENCES faq(id) ON DELETE CASCADE,
  cycle_code VARCHAR(255) NOT NULL REFERENCES cycle(code) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (faq_id, cycle_code)
);

CREATE TABLE faq_scenario (
  faq_id INT NOT NULL REFERENCES faq(id) ON DELETE CASCADE,
  scenario_code VARCHAR(255) NOT NULL REFERENCES scenario(code) ON DELETE CASCADE,
  position INT NOT NULL,
  PRIMARY KEY (faq_id, scenario_code)
);

CREATE INDEX idx_campaign_scenario_scenario_code ON campaign_scenario(scenario_code);
CREATE INDEX idx_scenario_campaign_code ON scenario(campaign_code);
CREATE INDEX idx_scenario_encounter_set_encounter_code ON scenario_encounter_set(encounter_code);
CREATE INDEX idx_scenario_encounter_set_card_card_id ON scenario_encounter_set_card(card_id);
CREATE INDEX idx_errata_card_card_id ON errata_card(card_id);
CREATE INDEX idx_errata_cycle_cycle_code ON errata_cycle(cycle_code);
CREATE INDEX idx_errata_scenario_scenario_code ON errata_scenario(scenario_code);
CREATE INDEX idx_faq_card_card_id ON faq_card(card_id);
CREATE INDEX idx_faq_cycle_cycle_code ON faq_cycle(cycle_code);
CREATE INDEX idx_faq_scenario_scenario_code ON faq_scenario(scenario_code);

-- migrate:down
