/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type ModerationActionScope = "account";

export type ModerationActionType = "ban" | "warning";

export type PgbossJobState =
  | "active"
  | "cancelled"
  | "completed"
  | "created"
  | "failed"
  | "retry";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_activity_at: Generated<Timestamp>;
  name: string;
  profile_completed_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp>;
}

export interface AccountFolder {
  account_id: string;
  revision: Generated<string>;
  state: Json;
}

export interface AccountIdentity {
  account_id: string;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  password_hash: string | null;
  pending_email: string | null;
  provider: string;
  provider_user_id: string | null;
  state: Json | null;
  updated_at: Generated<Timestamp>;
  verified_at: Timestamp | null;
}

export interface AccountModerationAction {
  account_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  end_reason: string | null;
  ended_by: string | null;
  ends_at: Timestamp | null;
  id: Generated<string>;
  reason: string;
  scope: ModerationActionScope;
  type: ModerationActionType;
}

export interface AccountSettings {
  account_id: string;
  collection: Json | null;
  revision: Generated<string>;
  settings: Json | null;
}

export interface ArkhamdbDeckAdditionalMetadata {
  data: Json;
  deck_id: number;
  id: Generated<string>;
}

export interface ArkhamdbDecklist {
  canonical_investigator_code: string;
  date_creation: Timestamp;
  date_update: Timestamp | null;
  description_md: string | null;
  description_word_count: Generated<number>;
  exile_string: string | null;
  id: number;
  ignore_deck_limit_slots: Record<string, number> | null;
  investigator_code: string;
  investigator_name: string;
  is_duplicate: Generated<boolean | null>;
  is_searchable: Generated<boolean | null>;
  like_count: Generated<number>;
  meta: Json | null;
  name: string;
  next_deck: number | null;
  previous_deck: number | null;
  side_slots: Record<string, number> | null;
  slots: Record<string, number>;
  taboo_id: number | null;
  tags: string | null;
  user_id: number;
  version: string | null;
  xp: number | null;
  xp_adjustment: number | null;
  xp_required: number | null;
  xp_spent: number | null;
}

export interface ArkhamdbDeckSnapshot {
  account_identity_id: string;
  created_at: Generated<Timestamp>;
  decks: Json;
  id: Generated<string>;
  last_modified: string | null;
}

export interface ArkhamdbRankingCache {
  id: Generated<number>;
  max_like_count: number;
  max_reputation: number;
  updated_at: Generated<Timestamp>;
}

export interface ArkhamdbUser {
  id: number;
  name: string;
  reputation: Generated<number>;
}

export interface Campaign {
  code: string;
  name: string;
  translations: { locale: string; name: string }[];
}

export interface CampaignScenario {
  campaign_code: string;
  position: number;
  scenario_code: string;
}

export interface Card {
  abbreviation: string | null;
  alternate_of: string | null;
  attachments: Json | null;
  back_flavor: string | null;
  back_illustrator: string | null;
  back_link: string | null;
  back_name: string | null;
  back_subname: string | null;
  back_text: string | null;
  back_traits: string | null;
  back_type: string | null;
  bonded_count: number | null;
  bonded_to: string | null;
  clues: number | null;
  clues_fixed: Generated<boolean | null>;
  code: string;
  cost: number | null;
  customization_change: string | null;
  customization_options: Json | null;
  customization_text: string | null;
  deck_limit: number | null;
  deck_options: Json | null;
  deck_requirements: string | null;
  doom: number | null;
  doom_per_investigator: boolean | null;
  double_sided: Generated<boolean | null>;
  duplicate_of: string | null;
  encounter_code: string | null;
  encounter_position: number | null;
  enemy_damage: number | null;
  enemy_evade: number | null;
  enemy_evade_per_investigator: boolean | null;
  enemy_fight: number | null;
  enemy_fight_per_investigator: boolean | null;
  enemy_horror: number | null;
  errata_date: Timestamp | null;
  exceptional: Generated<boolean | null>;
  exile: Generated<boolean | null>;
  faction_code: string;
  faction2_code: string | null;
  faction3_code: string | null;
  flavor: string | null;
  health: number | null;
  health_per_investigator: Generated<boolean | null>;
  hidden: Generated<boolean | null>;
  id: string;
  illustrator: string | null;
  is_unique: Generated<boolean | null>;
  myriad: Generated<boolean | null>;
  name: string;
  official: Generated<boolean>;
  pack_code: string;
  pack_position: number | null;
  permanent: Generated<boolean | null>;
  position: number;
  preview: Generated<boolean | null>;
  quantity: number;
  reprint_of: string | null;
  restrictions: string | null;
  sanity: number | null;
  shroud: number | null;
  shroud_per_investigator: boolean | null;
  side_deck_options: Json | null;
  side_deck_requirements: string | null;
  skill_agility: number | null;
  skill_combat: number | null;
  skill_intellect: number | null;
  skill_wild: number | null;
  skill_willpower: number | null;
  slot: string | null;
  stage: number | null;
  starts_in_hand: boolean | null;
  starts_in_play: boolean | null;
  sticky_mulligan: boolean | null;
  subname: string | null;
  subtype_code: string | null;
  taboo_set_id: number | null;
  taboo_text_change: string | null;
  taboo_xp: number | null;
  tags: string | null;
  text: string | null;
  traits: string | null;
  translations: { locale: string; [key: string]: string }[];
  type_code: string;
  vengeance: number | null;
  victory: number | null;
  xp: number | null;
}

export interface CardResolution {
  id: string;
  resolves_to: string;
}

export interface Cycle {
  code: string;
  name: string;
  position: number;
  translations: { locale: string; name: string }[];
}

export interface DataVersion {
  card_count: number;
  cards_updated_at: Timestamp;
  ingested_commit_id: string | null;
  locale: string;
  translation_updated_at: Timestamp;
}

export interface Deck {
  account_id: string | null;
  created_at: Generated<Timestamp>;
  description: Generated<string | null>;
  exile_string: string | null;
  id: Generated<string>;
  ignore_deck_limit: Json | null;
  investigator_code: string;
  investigator_name: string;
  meta: Json | null;
  name: string;
  next_deck: string | null;
  prev_deck: string | null;
  problem: string | null;
  provider_type: string;
  side_slots: Json | null;
  slots: Json;
  taboo_set_id: number | null;
  tags: string | null;
  updated_at: Generated<Timestamp>;
  version: string | null;
  xp: number | null;
  xp_adjustment: number | null;
  xp_spent: number | null;
}

export interface EncounterSet {
  code: string;
  name: string;
  pack_code: string;
  translations: { locale: string; name: string }[];
}

export interface Errata {
  citation: string;
  id: Generated<number>;
  position: number;
  ruling: string;
  section: string | null;
  type: string;
}

export interface ErrataCard {
  card_id: string;
  errata_id: number;
  position: number;
}

export interface ErrataCycle {
  cycle_code: string;
  errata_id: number;
  position: number;
}

export interface ErrataScenario {
  errata_id: number;
  position: number;
  scenario_code: string;
}

export interface Faction {
  code: string;
  is_primary: boolean;
  name: string;
  translations: Json;
}

export interface FanMadeProjectInfo {
  bucket_path: string;
  id: string;
  meta: Json;
}

export interface Faq {
  citation: string;
  id: Generated<number>;
  position: number;
  question: string;
  ruling: string;
  type: Generated<string>;
}

export interface FaqCard {
  card_id: string;
  faq_id: number;
  position: number;
}

export interface FaqCycle {
  cycle_code: string;
  faq_id: number;
  position: number;
}

export interface FaqScenario {
  faq_id: number;
  position: number;
  scenario_code: string;
}

export interface GrimoireEntry {
  citation: string;
  id: string;
  section: string;
  text: string | null;
  title: string;
  translations: { locale: string; title?: string; text?: string }[];
}

export interface GrimoireEntryReference {
  position: number;
  source_id: string;
  target_id: string;
}

export interface GrimoireSection {
  citation: string | null;
  id: string;
  position: number;
  text: string | null;
  title: string;
  translations: { locale: string; title?: string; text?: string }[];
}

export interface OauthToken {
  access_token: string;
  account_identity_id: string;
  created_at: Generated<Timestamp>;
  refresh_token: string | null;
  token_expires_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface Pack {
  chapter: number | null;
  code: string;
  cycle_code: string;
  date_release: Timestamp | null;
  name: string;
  position: number;
  reprint_packs: string[] | null;
  reprint_type: string | null;
  size: number | null;
  translations: { locale: string; name: string }[];
  type: string | null;
}

export interface PackType {
  pack_type: string;
}

export interface PgbossBam {
  command: string;
  completed_on: Timestamp | null;
  created_on: Generated<Timestamp>;
  error: string | null;
  id: Generated<string>;
  name: string;
  queue: string | null;
  started_on: Timestamp | null;
  status: Generated<string>;
  table_name: string;
  version: number;
}

export interface PgbossJob {
  completed_on: Timestamp | null;
  created_on: Generated<Timestamp>;
  data: Json | null;
  dead_letter: string | null;
  deletion_seconds: Generated<number>;
  expire_seconds: Generated<number>;
  group_id: string | null;
  group_tier: string | null;
  heartbeat_on: Timestamp | null;
  heartbeat_seconds: number | null;
  id: Generated<string>;
  keep_until: Generated<Timestamp>;
  name: string;
  output: Json | null;
  policy: string | null;
  priority: Generated<number>;
  retry_backoff: Generated<boolean>;
  retry_count: Generated<number>;
  retry_delay: Generated<number>;
  retry_delay_max: number | null;
  retry_limit: Generated<number>;
  singleton_key: string | null;
  singleton_on: Timestamp | null;
  start_after: Generated<Timestamp>;
  started_on: Timestamp | null;
  state: Generated<PgbossJobState>;
}

export interface PgbossQueue {
  active_count: Generated<number>;
  created_on: Generated<Timestamp>;
  dead_letter: string | null;
  deferred_count: Generated<number>;
  deletion_seconds: number;
  expire_seconds: number;
  heartbeat_seconds: number | null;
  maintain_on: Timestamp | null;
  monitor_on: Timestamp | null;
  name: string;
  partition: boolean;
  policy: string;
  queued_count: Generated<number>;
  retention_seconds: number;
  retry_backoff: boolean;
  retry_delay: number;
  retry_delay_max: number | null;
  retry_limit: number;
  singletons_active: string[] | null;
  table_name: string;
  total_count: Generated<number>;
  updated_on: Generated<Timestamp>;
  warning_queued: Generated<number>;
}

export interface PgbossSchedule {
  created_on: Generated<Timestamp>;
  cron: string;
  data: Json | null;
  key: Generated<string>;
  name: string;
  options: Json | null;
  timezone: string | null;
  updated_on: Generated<Timestamp>;
}

export interface PgbossSubscription {
  created_on: Generated<Timestamp>;
  event: string;
  name: string;
  updated_on: Generated<Timestamp>;
}

export interface PgbossVersion {
  bam_on: Timestamp | null;
  cron_on: Timestamp | null;
  version: number;
}

export interface PgbossWarning {
  created_on: Generated<Timestamp>;
  data: Json | null;
  id: Generated<string>;
  message: string;
  type: string;
}

export interface RulesVersion {
  citation: string;
  date: Timestamp;
}

export interface Scenario {
  campaign_code: string | null;
  code: string;
  name: string;
  translations: { locale: string; name: string }[];
}

export interface ScenarioEncounterSet {
  encounter_code: string;
  position: number;
  scenario_code: string;
}

export interface ScenarioEncounterSetCard {
  card_id: string;
  encounter_code: string;
  position: number;
  scenario_code: string;
}

export interface SchemaMigrations {
  version: string;
}

export interface Session {
  account_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  last_activity_at: Generated<Timestamp>;
  token_hash: string;
}

export interface Subtype {
  code: string;
  name: string;
  translations: Json;
}

export interface TabooSet {
  card_count: number;
  code: string;
  date_start: Timestamp;
  id: number;
  name: string | null;
}

export interface Type {
  code: string;
  name: string;
  translations: Json;
}

export interface VerificationToken {
  account_identity_id: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  token_type: string;
}

export interface DB {
  account: Account;
  account_folder: AccountFolder;
  account_identity: AccountIdentity;
  account_moderation_action: AccountModerationAction;
  account_settings: AccountSettings;
  arkhamdb_deck_additional_metadata: ArkhamdbDeckAdditionalMetadata;
  arkhamdb_deck_snapshot: ArkhamdbDeckSnapshot;
  arkhamdb_decklist: ArkhamdbDecklist;
  arkhamdb_ranking_cache: ArkhamdbRankingCache;
  arkhamdb_user: ArkhamdbUser;
  campaign: Campaign;
  campaign_scenario: CampaignScenario;
  card: Card;
  card_resolution: CardResolution;
  cycle: Cycle;
  data_version: DataVersion;
  deck: Deck;
  encounter_set: EncounterSet;
  errata: Errata;
  errata_card: ErrataCard;
  errata_cycle: ErrataCycle;
  errata_scenario: ErrataScenario;
  faction: Faction;
  fan_made_project_info: FanMadeProjectInfo;
  faq: Faq;
  faq_card: FaqCard;
  faq_cycle: FaqCycle;
  faq_scenario: FaqScenario;
  grimoire_entry: GrimoireEntry;
  grimoire_entry_reference: GrimoireEntryReference;
  grimoire_section: GrimoireSection;
  oauth_token: OauthToken;
  pack: Pack;
  pack_type: PackType;
  "pgboss.bam": PgbossBam;
  "pgboss.job": PgbossJob;
  "pgboss.queue": PgbossQueue;
  "pgboss.schedule": PgbossSchedule;
  "pgboss.subscription": PgbossSubscription;
  "pgboss.version": PgbossVersion;
  "pgboss.warning": PgbossWarning;
  rules_version: RulesVersion;
  scenario: Scenario;
  scenario_encounter_set: ScenarioEncounterSet;
  scenario_encounter_set_card: ScenarioEncounterSetCard;
  schema_migrations: SchemaMigrations;
  session: Session;
  subtype: Subtype;
  taboo_set: TabooSet;
  type: Type;
  verification_token: VerificationToken;
}
