type: folder
model: folder
id: fl_AnZTrE4WyY
createdAt: 2026-04-20T09:55:47.652395
updatedAt: 2026-04-20T09:55:47.652396
workspaceId: wk_bBoraEVHnK
folderId: null
authentication: {}
authenticationType: null
description: ''
headers: []
name: Cache
sortPriority: -1776678947650.0
