type: http_request
model: http_request
id: rq_ListOAuthClients
createdAt: 2026-07-21T22:35:02.000000
updatedAt: 2026-07-21T22:35:02.000000
workspaceId: wk_bBoraEVHnK
folderId: fl_OAuthClients
authentication: {}
authenticationType: null
body: {}
bodyType: null
description: ''
headers:
- enabled: true
  name: Authorization
  value: Bearer ${[ admin_api_key ]}
  id: OAuthListAuth
method: GET
name: List OAuth clients
sortPriority: 1000.0
url: ${[ base_url ]}/admin/oauth/clients
urlParameters: []
settingSendCookies:
  enabled: false
  value: true
settingStoreCookies:
  enabled: false
  value: true
settingValidateCertificates:
  enabled: false
  value: true
settingFollowRedirects:
  enabled: false
  value: true
settingRequestTimeout:
  enabled: false
  value: 0
