type: http_request
model: http_request
id: rq_4ndkhSmk9Q
createdAt: 2026-04-20T09:56:52.264537
updatedAt: 2026-04-21T13:48:44.581542
workspaceId: wk_bBoraEVHnK
folderId: fl_AnZTrE4WyY
authentication: {}
authenticationType: null
body: {}
bodyType: null
description: ''
headers: []
method: GET
name: Metadata (Localized)
sortPriority: 3000.0
url: ${[ base_url ]}/v1/cache/metadata/de
urlParameters: []
