type: http_request
model: http_request
id: rq_SetAccountSettingsFlag
createdAt: 2026-06-30T00:15:00
updatedAt: 2026-06-30T00:15:00.000000
workspaceId: wk_bBoraEVHnK
folderId: fl_k2Yxg7LqPm
authentication: {}
authenticationType: null
body:
  text: |
    {
      "username": "fffelice",
      "flag": "exampleFlag",
      "value": true
    }
bodyType: application/json
description: ''
headers:
- enabled: true
  name: Authorization
  value: Bearer ${[ admin_api_key ]}
  id: Tv8Bn2KqLc
- enabled: true
  name: Content-Type
  value: application/json
  id: Xp4Rw9MzQs
method: POST
name: Set account settings flag
sortPriority: 5000.005
url: ${[ base_url ]}/admin/account_settings/flags
urlParameters: []
settingSendCookies:
  enabled: false
  value: true
settingStoreCookies:
  enabled: false
  value: true
settingValidateCertificates:
  enabled: false
  value: true
settingFollowRedirects:
  enabled: false
  value: true
settingRequestTimeout:
  enabled: false
  value: 0
