name: "[Backend] Deploy"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: "package.json"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: false
      - uses: 1password/install-cli-action@v3
      - run: gem install kamal
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - run: npm ci
      - working-directory: backend
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_ACCOUNT: ${{ secrets.OP_ACCOUNT }}
          OP_VAULT: ${{ secrets.OP_VAULT }}
          OP_ITEM: ${{ secrets.OP_ITEM }}
        run: kamal deploy
