name: End to end tests (production)

on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      VITE_PAGE_NAME: ${{ vars.VITE_PAGE_NAME }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      VITE_CARD_IMAGE_URL: ${{ vars.VITE_CARD_IMAGE_URL }}
      E2E_BASE_URL: ${{ vars.PRODUCTION_BASE_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm ci
      - run: npm run prepare:e2e
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
