name: "[Fullstack E2E] Tests"

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - "shared/**"
      - "test/fullstack/**"
      - ".github/workflows/fullstack-e2e-tests.yml"

jobs:
  e2e:
    name: Fullstack End-to-End Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
      - run: |
          if [ ! -d test/fullstack/arkhamdb-docker ]; then
            git clone --depth 1 --recurse-submodules --shallow-submodules "$(git config --file .gitmodules --get submodule.test/fullstack/arkhamdb-docker.url)" test/fullstack/arkhamdb-docker
          fi
      - run: npm run test:fullstack:docker
      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: playwright-report-fullstack-e2e
          path: playwright-report/
