name: End-to-end tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      VITE_PAGE_NAME: ${{ vars.VITE_PAGE_NAME }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      VITE_CARD_IMAGE_URL: ${{ vars.VITE_CARD_IMAGE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
